In [1]:
import pandas as pd
import numpy as np
#df_org=pd.read_csv(filepath+"application_train_merge_clear_nomissing .csv")
df_org=pd.read_csv("application_train_merge_clear_nomissing_with_ylabel_dy.csv")

In [2]:
df=df_org

In [3]:
df.head()

,Unnamed: 0.1,Unnamed: 0,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_EDUCATION_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,...,PORTFOLIO_Cash,PORTFOLIO_POS,YIELD_high,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START_y,WEEKDAY_APPR_PROCESS_START,NAME_TYPE_SUITE,simple_labelx,scores
0,0,0,100002,1.0,0.0,202500.0,1.0,-9461.0,-637.0,-3648.0,...,0.000000,1.000000,0.000000,1.000000,0.000000,9.0,6.0,0.0,0.0,96
1,1,1,100003,0.0,0.0,270000.0,3.0,-16765.0,-1188.0,-1186.0,...,0.333333,0.666667,0.000000,0.333333,0.666667,12.0,5.0,1.0,0.0,100
2,2,2,100004,0.0,0.0,67500.0,1.0,-19046.0,-225.0,-4260.0,...,0.000000,1.000000,0.000000,0.000000,1.000000,5.0,5.0,0.0,0.0,100
3,3,3,100006,0.0,0.0,135000.0,1.0,-19005.0,-3039.0,-9833.0,...,0.500000,0.333333,0.333333,0.333333,0.166667,15.0,4.0,0.0,0.0,96
4,4,4,100007,0.0,0.0,121500.0,1.0,-19932.0,-3038.0,-4311.0,...,0.666667,0.333333,0.500000,0.000000,0.500000,13.0,7.0,0.0,0.0,88

## filter

In [40]:
corr_features = set()

# 建立相關矩陣
corr_matrix = X.corr()

for i in range(len(corr_matrix .columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > 0.9:
            colname = corr_matrix.columns[i]
            corr_features.add(colname)
            
X.drop(labels=corr_features, axis=1, inplace=True)

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_EDUCATION_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_EMP_PHONE,FLAG_WORK_PHONE,...,DAYS_PERIOD_median,CONTRACT_Cash_loans,CONTRACT_Revolving_loans,Cash through the bank,Non-cash from your account,YIELD_high,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START_y,WEEKDAY_APPR_PROCESS_START
115762,0.0,1.0,157500.0,3.0,-12741.0,-5507.0,-1392.0,-2491.0,1.0,0.0,...,240.0,0.857143,0.142857,0.857143,0.0,0.571429,0.142857,0.142857,18.0,4.0
115763,0.0,0.0,58500.0,1.0,-14582.0,-1701.0,-3449.0,-5264.0,1.0,0.0,...,330.0,0.750000,0.000000,0.750000,0.0,0.250000,0.250000,0.500000,8.0,1.0
115764,1.0,1.0,144000.0,3.0,-13416.0,-2405.0,-500.0,-4704.0,1.0,1.0,...,270.0,0.727273,0.000000,0.909091,0.0,0.272727,0.000000,0.636364,12.0,3.0
115765,0.0,1.0,81000.0,3.0,-10567.0,-3855.0,-1260.0,-2188.0,1.0,0.0,...,135.0,0.250000,0.000000,0.750000,0.0,0.250000,0.000000,0.500000,12.0,2.0
115766,0.0,1.0,292500.0,3.0,-16010.0,-1185.0,-5034.0,-4392.0,1.0,0.0,...,46.0,0.000000,0.000000,1.000000,0.0,0.200000,0.200000,0.200000,16.0,7.0
115767,0.0,0.0,81000.0,3.0,-9874.0,-1928.0,-9445.0,-2557.0,1.0,0.0,...,60.0,0.000000,0.000000,1.000000,0.0,0.750000,0.000000,0.000000,13.0,1.0
115768,0.0,0.0,261000.0,3.0,-20390.0,-5326.0,-157.0,-3906.0,1.0,0.0,...,176.0,0.846154,0.076923,0.923077,0.0,0.384615,0.307692,0.230769,10.0,1.0
115769,0.0,0.0,153000.0,1.0,-16705.0,-7258.0,-9798.0,-259.0,1.0,0.0,...,240.0,0.500000,0.250000,0.750000,0.0,0.250000,0.000000,0.250000,16.0,5.0
115770,0.0,0.0,153000.0,3.0,-14966.0,-7921.0,-6737.0,-5150.0,1.0,0.0,...,120.0,0.000000,0.000000,1.000000,0.0,1.000000,0.000000,0.000000,12.0,6.0
115771,0.0,0.0,157500.0,3.0,-16856.0,-1262.0,-5128.0,-410.0,1.0,1.0,...,135.0,0.500000,0.125000,0.875000,0.0,0.250000,0.250000,0.375000,14.0,5.0

In [42]:
corr_features = set()

# 建立相關矩陣
corr_matrix = X.corr(method='spearman')

for i in range(len(corr_matrix .columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > 0.8:
            colname = corr_matrix.columns[i]
            corr_features.add(colname)
            
X.drop(labels=corr_features, axis=1, inplace=True)

### 方差特徵

In [17]:
from sklearn.feature_selection import VarianceThreshold
selector=VarianceThreshold(threshold=(0.8*(1-0.8)))
selector.fit_transform(X,y)
selector.get_support (indices= False )

array([ True,  True,  True,  True,  True,  True,  True, False, False,
        True, False,  True, False, False, False,  True,  True, False,
        True, False, False,  True,  True,  True, False,  True,  True,
        True, False, False, False,  True, False,  True, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
        True,  True, False, False,  True,  True,  True,  True, False,
       False,  True,  True,  True, False, False, False, False, False,
       False, False,  True,  True])

In [18]:
from sklearn.feature_selection import SelectKBest,mutual_info_classif,f_classif
X_new = SelectKBest(f_classif, k=20).fit(X,y)

In [19]:
features=X.columns[X_new.get_support()]

In [20]:
features

Index(['NAME_EDUCATION_TYPE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE',
       'AMT_REQ_CREDIT_BUREAU_YEAR', 'NAME_CONTRACT_TYPE_Cash loans',
       'NAME_FAMILY_STATUS_Single / not married',
       'HOUSETYPE_MODE_block of flats', 'PREV_ANNUITY_median',
       'PREV_APPLICATION_max', 'PREV_DOWN_PAYMENT_median', 'PREV_CRE/APP_max',
       'DAYS_DECISION_median', 'DAYS_PERIOD_median', 'CONTRACT_Cash_loans',
       'YIELD_high', 'YIELD_low', 'YIELD_middle', 'HOUR_APPR_PROCESS_START_y'],
      dtype='object')

## 切分資料

In [54]:
y_=[]#找出 違約人的索引
for i in (df[df["simple_labelx"]!=0].index):
  y_.append(i)
y_1=[] #找出沒違約人的索引
for i in (df[df["simple_labelx"]==0].index):
  y_1.append(i)
df_split=df.loc[y_]
df_split0=df.loc[y_1]
df_tar1=df_split.reset_index()
df_tar0=df_split0.reset_index()
df_tar_e=df_tar0.iloc[42114:100000,:] #分成同等分
dfe=pd.concat([df_tar_e,df_tar1],ignore_index=True,axis=0)

In [55]:
df_X = dfe.iloc[:,5:-3]
df_y = dfe['simple_labelx']

In [56]:
#資料範例分割
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
#X , y = df.iloc[:,4:-3] , df.iloc[:,-2]
X , y =df_X,df_y

In [52]:
X_train, X_test, y_train, y_test =\
    train_test_split(X, y, 
                     test_size=0.2,#超過10萬9,1分比較好 
                     random_state=0, 
                     stratify=y)
X_train= stdsc.fit_transform(X_train)
X_test= stdsc.transform(X_test)

## RFE

In [ ]:
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
# create pipeline
rfe = RFE(estimator=RandomForestClassifier(n_estimators=100,max_depth=6, random_state=0,criterion='entropy'), n_features_to_select=10)
model = RandomForestClassifier(n_estimators=100,max_depth=2, random_state=0,criterion='entropy')
pipeline = Pipeline(steps=[('s',rfe),('m',model)])
pipeline.fit(X,y)
# evaluate model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=3, n_jobs=-1, error_score='raise')
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

In [11]:
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
# create pipeline
rfe = RFE(estimator=DecisionTreeClassifier(), n_features_to_select=10)
model = DecisionTreeClassifier()
pipeline = Pipeline(steps=[('s',rfe),('m',model)])
pipeline.fit(X,y)
# evaluate model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=3, n_jobs=-1, error_score='raise')
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.712 (0.001)

In [12]:
rfe.get_support()

array([False, False, False,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
        True, False, False,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [13]:
features_ref=X.columns[rfe.get_support()]

In [14]:
features_ref

Index(['DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH',
       'DAYS_LAST_PHONE_CHANGE', 'PREV_ANNUITY_median', 'PREV_CREDIT_max',
       'PREV_CREDIT_sum', 'PREV_CRE/APP_max', 'DAYS_DECISION_median'],
      dtype='object')

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
df_X = df[['DAYS_LAST_PHONE_CHANGE', 'DAYS_LATE_PAYMENT', 'PC_SK_DPDMix_Max',
       'SK_ID_PREV_y', 'bureau_DAYS_CREDIT']]
df_y = df['simple_labelx']

## RFECV

In [ ]:

from sklearn.feature_selection import RFECV
from sklearn.svm import SVR

estimator = SVR(kernel="linear")
selector = RFECV(estimator, step=1, cv=10)
selector = selector.fit(X, y)
selector.support_

selector.ranking_